version: '3'

services:
  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    volumes:
      - ./ansible/playbooks:/ansible/playbooks
    networks:
      - backend
    depends_on:
      - ubuntu
      - centos

  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    networks:
      - backend

  centos:
    build:
      context: ./centos
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  backend:
